on: 
  pull_request: 
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: Login
      uses: okteto/login@main
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Delete namespace
      uses: okteto/destroy-preview@main
      with:
        name: pr-${{ github.event.number }}-aadi308
